### PR TITLE
This PR is a significant refactor to delayer the repo and remove clutter. 

### PR DESCRIPTION
**Pull request by jeromelecoq**
1. It removes the CLI which has made the code base hard to maintain and provided limited value
2. It removes the JSON layer to facilitate scripting
3. It removes historical scripts since they are not compatible with the updated structure. 
4. Remove unnecessary packages and dependencies.

### CODE REVIEW

**Comment by jeromelecoq** [comment]
Latest commit added back caching to make inferrence 10x faster

**Comment by jeromelecoq** [comment]
I edited the tests since this version now outputs a non-full batch on the edges. 
IE. the last batch in a range of samples could be smaller than the requested batch size. 
I think this behavior is superior as it uses the entire provided data.

**Comment by mikejhuang** [comment]
> I edited the tests since this version now outputs a non-full batch on the edges. IE. the last batch in a range of samples could be smaller than the requested batch size. I think this behavior is superior as it uses the entire provided data.

Hey, I noticed your PR doesn't seem to be tracking the files from the previous merged PR into master. 

The incomplete batches issue was addressed from the previous PR
https://github.com/AllenInstitute/deepinterpolation/blame/7ee87ef33d5eecb7be382f9085ff855355da6dc7/tests/test_inference_collection.py#L271

**Comment by jeromelecoq** [comment]
> > I edited the tests since this version now outputs a non-full batch on the edges. IE. the last batch in a range of samples could be smaller than the requested batch size. I think this behavior is superior as it uses the entire provided data.
> 
> Hey, I noticed your PR doesn't seem to be tracking the files from the previous merged PR into master.
> 
> The incomplete batches issue was addressed from the previous PR https://github.com/AllenInstitute/deepinterpolation/blame/7ee87ef33d5eecb7be382f9085ff855355da6dc7/tests/test_inference_collection.py#L271

Yes, thanks for pointing that out. This is a big refactor so I had to go back a bit. 

Looks like flattening the repo also fixed the hanging thread issue. So far it is gone in my tests.

**Comment by jeromelecoq** [comment]
Plan is to share docker through code ocean capsule separately. So I am not going to add a docker quite yet.

**Pull request merged**
