### PR TITLE
Combined inference optimizations

### PR DESCRIPTION
**Pull request by mikejhuang**

### CODE REVIEW

**Comment by jeromelecoq** [comment]
I am getting an error on my test inference set : 

+ python -u run_denoising.py
2023-04-05 17:46:12.871225: W tensorflow/core/profiler/internal/smprofiler_timeline.cc:460] Initializing the SageMaker Profiler.
2023-04-05 17:46:12.884511: W tensorflow/core/profiler/internal/smprofiler_timeline.cc:105] SageMaker Profiler is not enabled. The timeline writer thread will not be started, future recorded events will be dropped.
2023-04-05 17:46:13.290512: W tensorflow/core/profiler/internal/smprofiler_timeline.cc:460] Initializing the SageMaker Profiler.
INFO:matplotlib.font_manager:generated new fontManager
1.1
['run_denoising.py']
nb_frame_inference :499
Original movie has 115770 frame(s).
target frame range is from frame 0 to 499
Preparing data for inference
INFO:root:randomize should be set to False for inference.                         Overriding the parameter
Starting inference from local frame:0 to frame: 499
INFO:Inference:wrote ../results/inference_full_args.json
2023-04-05 17:46:17.619047: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX512F
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-04-05 17:46:17.853517: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-04-05 17:46:17.931844: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-04-05 17:46:17.933534: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-04-05 17:46:20.269103: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-04-05 17:46:20.270848: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-04-05 17:46:20.272348: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-04-05 17:46:20.274493: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1510] Created device /device:GPU:0 with 13598 MB memory:  -> device: 0, name: Tesla T4, pci bus id: 0000:00:1e.0, compute capability: 7.5
WARNING:Inference:GPU is available, multiprocessing is disabled
INFO:Inference:wrote ../results/2023_04_05_17_46_inference.json
INFO:Inference:wrote ../results/2023_04_05_17_46_generator.json
INFO:deepinterpolation.inferrence_collection:Created empty HDF5 file ../results/ophys-movie-denoised-from-0000000-to-0000499.h5
INFO:Inference:created objects for inference
2023-04-05 17:46:23.231110: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-04-05 17:46:23.232880: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-04-05 17:46:23.234363: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-04-05 17:46:23.236097: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-04-05 17:46:23.237614: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-04-05 17:46:23.239083: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-04-05 17:46:23.240610: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-04-05 17:46:23.242113: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-04-05 17:46:23.243571: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1510] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 13598 MB memory:  -> device: 0, name: Tesla T4, pci bus id: 0000:00:1e.0, compute capability: 7.5
  0%|          | 0/470 [00:00<?, ?it/s]2023-04-05 17:46:26.548214: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:185] None of the MLIR Optimization Passes are enabled (registered 2)
2023-04-05 17:46:28.031110: I tensorflow/stream_executor/cuda/cuda_dnn.cc:369] Loaded cuDNN version 8100
  2%|▏         | 11/470 [00:39<27:44,  3.63s/it] 
Traceback (most recent call last):
  File "run_denoising.py", line 194, in <module>
    inference_obj.run()
  File "/usr/local/lib/python3.8/site-packages/deepinterpolation/cli/inference.py", line 63, in run
    inferrence_class.run()
  File "/usr/local/lib/python3.8/site-packages/deepinterpolation/inferrence_collection.py", line 382, in run
    local_data = self.generator_obj[index_dataset]
  File "/usr/local/lib/python3.8/site-packages/deepinterpolation/generator_collection.py", line 969, in __getitem__
    shuffle_indexes = self.generate_batch_indexes(index)
  File "/usr/local/lib/python3.8/site-packages/deepinterpolation/generator_collection.py", line 544, in generate_batch_indexes
    shuffle_indexes = self.list_samples[indexes]
IndexError: index 511 is out of bounds for axis 0 with size 470

**Comment by jeromelecoq** [comment]
training code seems to complete with no errors

**Comment by jeromelecoq** [comment]
> I am getting an error on my test inference set :
> 
> * python -u run_denoising.py
>   2023-04-05 17:46:12.871225: W tensorflow/core/profiler/internal/smprofiler_timeline.cc:460] Initializing the SageMaker Profiler.
>   2023-04-05 17:46:12.884511: W tensorflow/core/profiler/internal/smprofiler_timeline.cc:105] SageMaker Profiler is not enabled. The timeline writer thread will not be started, future recorded events will be dropped.
>   2023-04-05 17:46:13.290512: W tensorflow/core/profiler/internal/smprofiler_timeline.cc:460] Initializing the SageMaker Profiler.
>   INFO:matplotlib.font_manager:generated new fontManager
>   1.1
>   ['run_denoising.py']
>   nb_frame_inference :499
>   Original movie has 115770 frame(s).
>   target frame range is from frame 0 to 499
>   Preparing data for inference
>   INFO:root:randomize should be set to False for inference.                         Overriding the parameter
>   Starting inference from local frame:0 to frame: 499
>   INFO:Inference:wrote ../results/inference_full_args.json
>   2023-04-05 17:46:17.619047: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX512F
>   To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
>   2023-04-05 17:46:17.853517: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
>   2023-04-05 17:46:17.931844: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
>   2023-04-05 17:46:17.933534: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
>   2023-04-05 17:46:20.269103: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
>   2023-04-05 17:46:20.270848: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
>   2023-04-05 17:46:20.272348: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
>   2023-04-05 17:46:20.274493: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1510] Created device /device:GPU:0 with 13598 MB memory:  -> device: 0, name: Tesla T4, pci bus id: 0000:00:1e.0, compute capability: 7.5
>   WARNING:Inference:GPU is available, multiprocessing is disabled
>   INFO:Inference:wrote ../results/2023_04_05_17_46_inference.json
>   INFO:Inference:wrote ../results/2023_04_05_17_46_generator.json
>   INFO:deepinterpolation.inferrence_collection:Created empty HDF5 file ../results/ophys-movie-denoised-from-0000000-to-0000499.h5
>   INFO:Inference:created objects for inference
>   2023-04-05 17:46:23.231110: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
>   2023-04-05 17:46:23.232880: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
>   2023-04-05 17:46:23.234363: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
>   2023-04-05 17:46:23.236097: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
>   2023-04-05 17:46:23.237614: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
>   2023-04-05 17:46:23.239083: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
>   2023-04-05 17:46:23.240610: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
>   2023-04-05 17:46:23.242113: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
>   2023-04-05 17:46:23.243571: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1510] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 13598 MB memory:  -> device: 0, name: Tesla T4, pci bus id: 0000:00:1e.0, compute capability: 7.5
>   0%|          | 0/470 [00:00<?, ?it/s]2023-04-05 17:46:26.548214: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:185] None of the MLIR Optimization Passes are enabled (registered 2)
>   2023-04-05 17:46:28.031110: I tensorflow/stream_executor/cuda/cuda_dnn.cc:369] Loaded cuDNN version 8100
>   2%|▏         | 11/470 [00:39<27:44,  3.63s/it]
>   Traceback (most recent call last):
>   File "run_denoising.py", line 194, in 
>   inference_obj.run()
>   File "/usr/local/lib/python3.8/site-packages/deepinterpolation/cli/inference.py", line 63, in run
>   inferrence_class.run()
>   File "/usr/local/lib/python3.8/site-packages/deepinterpolation/inferrence_collection.py", line 382, in run
>   local_data = self.generator_obj[index_dataset]
>   File "/usr/local/lib/python3.8/site-packages/deepinterpolation/generator_collection.py", line 969, in **getitem**
>   shuffle_indexes = self.generate_batch_indexes(index)
>   File "/usr/local/lib/python3.8/site-packages/deepinterpolation/generator_collection.py", line 544, in generate_batch_indexes
>   shuffle_indexes = self.list_samples[indexes]
>   IndexError: index 511 is out of bounds for axis 0 with size 470

I just double confirmed that the branch this PR is merging into could complete the same inference code.

**Comment by jeromelecoq** [comment]
This inference code is using the OphysGenerator object. Did you bring back the original object code? 
It looks like it but I am not entirely sure since this is a large PR.

**Comment by jeromelecoq** [comment]
I am suspecting this is due to the change logic to deal with the last batch of data during inference. I took care to make sure to single frame was discarded. This make it necessary to handle the last end frame by frame instead as a batch.

**Comment by jeromelecoq** [comment]
Likely culprit is steps_per_epoch since the core_inference code is using it to process datasets in groups of steps_per_epoch frames to parallelize. 
The new run code is not using it.

**Comment by jeromelecoq** [comment]
So here is I think are the tradeoff:
1. Old code would parallelize by using tensorflow built-in thread and would set steps_per_epoch to 50 or so and batch to 1. 
In this scenario, you have to make sure the last end of the movie (that is smaller than 50) is processed to avoid missing frames. 
2. New run code is using its own threading and the run code is just using predict on batch. So the only way to get faster is to set Batch to be larger than one. In that case, there will likely be a missing uncomplete batch at the end of the movie. This code is still crashing when steps_per_epoch is set to non-zero.

**Comment by mikejhuang** [comment]
> This inference code is using the OphysGenerator object. Did you bring back the original object code? It looks like it but I am not entirely sure since this is a large PR.

The generator object is defined in the generator_params from the input json. This needs to be modified to use `InferenceOphysGenerator`

e.g.:
```
  "generator_params": {
    "gpu_cache_full": false,
    "normalize_cache": false,
    "batch_size": 8,
    "name": "InferenceOphysGenerator",
    "start_frame": 0,
    "end_frame": 10000,
    "randomize": false,
    "data_path": "/mnt/c/users/astro/Projects/1229768304_suite2p_motion_output.h5"
  }
```

**Comment by mikejhuang** [comment]
> I am getting an error on my test inference set :
> 
>   Traceback (most recent call last):
>   File "run_denoising.py", line 194, in 
>   inference_obj.run()
>   File "/usr/local/lib/python3.8/site-packages/deepinterpolation/cli/inference.py", line 63, in run
>   inferrence_class.run()
>   File "/usr/local/lib/python3.8/site-packages/deepinterpolation/inferrence_collection.py", line 382, in run
>   local_data = self.generator_obj[index_dataset]
>   File "/usr/local/lib/python3.8/site-packages/deepinterpolation/generator_collection.py", line 969, in **getitem**
>   shuffle_indexes = self.generate_batch_indexes(index)
>   File "/usr/local/lib/python3.8/site-packages/deepinterpolation/generator_collection.py", line 544, in generate_batch_indexes
>   shuffle_indexes = self.list_samples[indexes]
>   IndexError: index 511 is out of bounds for axis 0 with size 470

What batch size did you use for this? I implemented some fixes that should have fixed this. But if your batch size is < 42, then my fix would not have addressed this.

**Pull request merged**
